#!/usr/bin/env bash
# script to install and setup nginx
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html;
}" > /etc/nginx/sites-available/default

service nginx restart
